package org.altruistas.awsiberiacruzroja.models.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.altruistas.awsiberiacruzroja.models.FormQuestions;
import org.altruistas.awsiberiacruzroja.models.GenderEnum;

import java.util.Date;
import java.util.List;

@Builder
@NoArgsConstructor
@AllArgsConstructor
@Data
@DynamoDBTable(tableName = "acogidas")
public class AcogidaEntity {
    @DynamoDBAttribute(attributeName = "acogida_id")
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String acogidaId;

    @DynamoDBAttribute(attributeName = "creation_date")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private Date creationDate;

    @DynamoDBAttribute(attributeName = "last_updated_date")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    private Date lastUpdatedDate;

    @DynamoDBAttribute(attributeName = "form_questions")
    private List<FormQuestions> formQuestions;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute(attributeName = "last_name")
    private String lastName;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute(attributeName = "phone_number")
    private String phoneNumber;

    @DynamoDBAttribute
    private String nif;

    @DynamoDBAttribute
    private Integer age;

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    private GenderEnum gender;
}
